#The Showcase plugin allows players to show off their prized possessions by storing them in a publicly
#viewable GUI.

messages:
  prefix: "&8[&5&lShowcase&8] &r"
  reload: "&7Showcase has been reloaded."
  no-permission: "&cYou do not have permission."
  player-not-created-showcase: "&7%player_name% has not created a showcase."
  player-has-never-joined: "&7%player_name% has never played on the server before."
  unknown-player: "&7Unknown player."