name: Showcase
version: '${project.version}'
main: dev.naspo.showcase.Showcase
api-version: 1.18
authors: [ Naspo ]
description: Show off your prized possessions.

depend:
  - Vault

softdepend:
  - PlaceholderAPI

commands:
  showcase:
